name: CI - Source & Examples - Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Environment
      run: | 
        mkdir build
        cd build
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Setup CMake Project
      run: cmake -G "Visual Studio 16 2019" -DSTATIC=ON -DSHARED=ON -DBUILD_EXAMPLES=ON -DBUILD_GAMES=OFF -DINCLUDE_EVERYTHING=ON ../raylib
    - name: Build raylib Source & Examples
      run: cmake --build . --target install
